sonar.projectKey=raytorresch_Adoptable-Landing
sonar.organization=raytorresch

sonar.qualitygate.wait=true
sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*
sonar.coverage.exclusions=**/*.test.tsx,**/*.test.ts,**/*.stories.tsx
